import {
  Dao,
  Baejji,
  Desyni,
  Eddi,
  Marid,
  Sugar,
  Miz,
  Mos,
  Ilyeong,
  Chenchen,
  Neo,
  Naiad,
  Reune,
  Hellios,
  Toreu,
  Daisy,
} from "./img";

const matchType: Record<
  string,
  { image: string; name: string; tag: string[] }
> = {
  ESFP: { name: "다오", image: Dao, tag: ["열혈", "밝음", "낙관"] },
  INTP: { name: "디지니", image: Desyni, tag: ["부끄럼", "과감"] },
  ISFP: { name: "배찌", image: Baejji, tag: ["단순", "낙관", "게으름"] },
  ISTJ: { name: "에띠", image: Eddi, tag: ["똑똑함", "박학다식", "설계"] },
  INFP: {
    name: "마리드",
    image: Marid,
    tag: ["도도", "낭만", "사랑"],
  },
  ENTJ: { name: "슈가", image: Sugar, tag: ["열정", "승리"] },
  ESTJ: {
    name: "미즈 로두마니",
    image: Miz,
    tag: ["리더", "뛰어난 기술", "고집"],
  },
  ISTP: { name: "모스", image: Mos, tag: ["튜닝 마스터", "손기술", "성실"] },
  ESTP: { name: "일영", image: Ilyeong, tag: ["대범", "거침없음", "명랑"] },
  ENFP: { name: "첸첸", image: Chenchen, tag: ["활발", "친절", "활동적"] },
  ESFJ: { name: "네오", image: Neo, tag: ["정의", "노력"] },
  INFJ: { name: "나이아드", image: Naiad, tag: ["내성적", "희망"] },
  ISFJ: { name: "르네", image: Reune, tag: ["내성적", "친구 좋아"] },
  INTJ: { name: "헬리오스", image: Hellios, tag: ["신비주의"] },
  ENTP: { name: "토르", image: Toreu, tag: ["용감", "자신감", "호쾌", "힘"] },
  ENFJ: { name: "데이지", image: Daisy, tag: ["친절", "관리자", "열정"] },
};

const friendMatchData: Record<string, { type: string; bestFriend: string }> = {
  다오: { type: "ESFP", bestFriend: "" },
  디지니: { type: "INTP", bestFriend: "" },
  배찌: { type: "ISFP", bestFriend: "" },
  에띠: { type: "ISTJ", bestFriend: "" },
  마리드: { type: "INFP", bestFriend: "" },
  슈가: { type: "ENTJ", bestFriend: "" },
  "미즈 로두마니": { type: "ESTJ", bestFriend: "" },
  일영: { type: "ESTP", bestFriend: "" },
  모스: { type: "ISTP", bestFriend: "" },
  첸첸: { type: "ENFP", bestFriend: "" },
  네오: { type: "ESFJ", bestFriend: "" },
  나이아드: { type: "INFJ", bestFriend: "" },
  르네: { type: "ISFJ", bestFriend: "" },
  헬리오스: { type: "INTJ", bestFriend: "" },
  토르: { type: "ENTP", bestFriend: "" },
  데이지: { type: "ENFJ", bestFriend: "" },
};

const character: Record<string, string> = {
  열혈: "#FFBFC3",
  밝음: "#FFEB99",
  낙관: "#A8E693",
  부끄럼: "#7FBFE6",
  과감: "#A288B3",
  단순: "#FCA5C0",
  게으름: "#FFBFC3",
  똑똑함: "#FFEB99",
  박학다식: "#A8E693",
  설계: "#7FBFE6",
  도도: "#A288B3",
  낭만: "#FCA5C0",
  사랑: "#FFBFC3",
  열정: "#FFAB99",
  승리: "#A8E693",
  리더: "#7FBFE6",
  "뛰어난 기술": "#A288B3",
  고집: "#FCA5C0",
  "튜닝 마스터": "#FFBFC3",
  손기술: "#FFEB99",
  성실: "#A8E693",
  대범: "#7FBFE6",
  거침없음: "#A288B3",
  명랑: "#FCA5C0",
  활발: "#FFBFC3",
  친절: "#FF6F99",
  활동적: "#A8E693",
  정의: "#7FBFE6",
  노력: "#A288B3",
  내성적: "#FCA5C0",
  희망: "#FFBFC3",
  "친구 좋아": "#FFEB99",
  신비주의: "#A8E693",
  용감: "#7FBFE6",
  자신감: "#A288B3",
  호쾌: "#FCA5C0",
  힘: "#FFBFC3",
  관리자: "#FFCC66",
};

export { matchType, friendMatchData, character };
