import {
  Dao,
  Baejji,
  Desyni,
  Eddi,
  Marid,
  Sugar,
  Miz,
  Mos,
  Ilyeong,
  Chenchen,
  Neo,
  Naiad,
  Reune,
  Hellios,
  Toreu,
  Daisy,
} from "./img";

const matchType: Record<
  string,
  { image: string; name: string; tag: string[]; mate: string; desc: string }
> = {
  ESFP: {
    name: "다오",
    image: Dao,
    tag: ["열혈", "밝음", "낙관"],
    mate: "INFP",
    desc: "사교적이고 활동적인 당신은 밝고 낙관적인 다오와 잘 어울려요!\n어떤 상황이든 잘 적응하고 사람들과 어울리는 것을  좋아해 누구와도 친구가 될 수 있어요. \n또한 표현력도 뛰어나고 공감 능력도 좋기 때문에 다른 사람들과 금방 친해질 수 있어요! \n\n당신의 카트 절친은 낭만있고 평화주의적인 마리드와 잘 어울려요 :)",
  },
  INTP: {
    name: "디지니",
    image: Desyni,
    tag: ["부끄럼", "과감"],
    mate: "ESTP",
    desc: "",
  },
  ISFP: {
    name: "배찌",
    image: Baejji,
    tag: ["단순", "낙관", "게으름"],
    mate: "ENFP",
    desc: "",
  },
  ISTJ: {
    name: "에띠",
    image: Eddi,
    tag: ["똑똑함", "박학다식", "설계"],
    mate: "ESFJ",
    desc: "",
  },
  INFP: {
    name: "마리드",
    image: Marid,
    tag: ["도도", "낭만", "사랑"],
    mate: "ESFP",
    desc: "",
  },
  ENTJ: {
    name: "슈가",
    image: Sugar,
    tag: ["열정", "승리"],
    mate: "INFJ",
    desc: "",
  },
  ESTJ: {
    name: "미즈 로두마니",
    image: Miz,
    tag: ["리더", "뛰어난 기술", "고집"],
    mate: "ISFJ",
    desc: "",
  },
  ISTP: {
    name: "모스",
    image: Mos,
    tag: ["튜닝 마스터", "손기술", "성실"],
    mate: "ENTP",
    desc: "",
  },
  ESTP: {
    name: "일영",
    image: Ilyeong,
    tag: ["대범", "거침없음", "명랑"],
    mate: "INTP",
    desc: "",
  },
  ENFP: {
    name: "첸첸",
    image: Chenchen,
    tag: ["활발", "친절", "활동적"],
    mate: "ISFP",
    desc: "",
  },
  ESFJ: {
    name: "네오",
    image: Neo,
    tag: ["정의", "노력"],
    mate: "ISTJ",
    desc: "",
  },
  INFJ: {
    name: "나이아드",
    image: Naiad,
    tag: ["내성적", "희망"],
    mate: "ENTJ",
    desc: "",
  },
  ISFJ: {
    name: "르네",
    image: Reune,
    tag: ["내성적", "친구 좋아"],
    mate: "ESTJ",
    desc: "",
  },
  INTJ: {
    name: "헬리오스",
    image: Hellios,
    tag: ["신비주의"],
    mate: "ENFJ",
    desc: "",
  },
  ENTP: {
    name: "토르",
    image: Toreu,
    tag: ["용감", "자신감", "호쾌", "힘"],
    mate: "ISTP",
    desc: "",
  },
  ENFJ: {
    name: "데이지",
    image: Daisy,
    tag: ["친절", "관리자", "열정"],
    mate: "INTJ",
    desc: "",
  },
};

const character: Record<string, string> = {
  열혈: "#FFBFC3",
  밝음: "#FFEB99",
  낙관: "#A8E693",
  부끄럼: "#7FBFE6",
  과감: "#A288B3",
  단순: "#FCA5C0",
  게으름: "#FFBFC3",
  똑똑함: "#FFEB99",
  박학다식: "#A8E693",
  설계: "#7FBFE6",
  도도: "#A288B3",
  낭만: "#FCA5C0",
  사랑: "#FFBFC3",
  열정: "#FFAB99",
  승리: "#A8E693",
  리더: "#7FBFE6",
  "뛰어난 기술": "#A288B3",
  고집: "#FCA5C0",
  "튜닝 마스터": "#FFBFC3",
  손기술: "#FFEB99",
  성실: "#A8E693",
  대범: "#7FBFE6",
  거침없음: "#A288B3",
  명랑: "#FCA5C0",
  활발: "#FFBFC3",
  친절: "#FF6F99",
  활동적: "#A8E693",
  정의: "#7FBFE6",
  노력: "#A288B3",
  내성적: "#FCA5C0",
  희망: "#FFBFC3",
  "친구 좋아": "#FFEB99",
  신비주의: "#A8E693",
  용감: "#7FBFE6",
  자신감: "#A288B3",
  호쾌: "#FCA5C0",
  힘: "#FFBFC3",
  관리자: "#FFCC66",
};

export { matchType, character };
